services:
  # Web Service (Node.js App)
  - type: web
    name: menu-builder-app
    runtime: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: / # Your app serves index.html at '/', which confirms it's running
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure random string
 